local palette = require("themes.nocturne-rose.palette")

return {
  ui = {
    bg_deep = palette.black,
    bg = palette.base,
    bg_inactive = palette.mantle,
    surface = palette.surface,
    overlay = palette.overlay,
    overlay_high = palette.overlay_high,
    text = palette.text,
    text_dim = palette.subtext,
    muted = palette.muted,
    disabled = palette.disabled,
    accent = palette.rose,
    accent_secondary = palette.orchid,
    search = palette.search,
    search_current = palette.search_current,
  },
  syntax = {
    text = palette.text,
    comment = palette.muted,
    punctuation = palette.subtext,
    func = palette.rose,
    keyword = palette.orchid,
    string = palette.green,
    type = palette.aqua,
    constant = palette.yellow,
    builtin = palette.blue,
  },
  diagnostic = {
    error = palette.red,
    warn = palette.yellow,
    info = palette.blue,
    hint = palette.aqua,
  },
  vcs = {
    add = palette.green,
    change = palette.blue,
    delete = palette.red,
  },
  diff = {
    add = palette.diff_add,
    delete = palette.diff_delete,
    change = palette.diff_change,
    text = palette.diff_text,
  },
  terminal = {
    palette.black,
    palette.red,
    palette.green,
    palette.yellow,
    palette.blue,
    palette.rose,
    palette.aqua,
    palette.text,
    palette.disabled,
    palette.red,
    palette.green,
    palette.yellow,
    palette.blue,
    palette.orchid,
    palette.aqua,
    palette.text,
  },
}
