---
name: "Obsidian Sync Settings"
command: 'cd ~/dev/dotfiles && ga config/obsidian && gc -m "update: sync obsidian settings" && gp && cd -'
description: Sync settings for Obsidian
arguments: []
tags: ["obsidian", "sync", "settings"]
source_url: ~
author: ~
author_url: ~
shells: []
