---
name: "Search files here in current directory by filename using fzf"
command: "find . -type f 2>/dev/null | fzf --preview 'bat --color=always --style=header,grid --line-range :100 {} 2>/dev/null || head -100 {}' --preview-window=right:50%:wrap"
description: "Search all files in current directory by filename using fzf. This will search all files in the current directory and display them in an interactive fzf interface."
arguments: []
tags: ["search", "fzf", "files", "find", "current", "here"]
source_url: ~
author: ~
author_url: ~
shells: []
