---
name: "Search content here in current directory . by content using fzf and ripgrep"
command: 'rg --line-number --no-heading --color=always --smart-case -. "$1" . 2>/dev/null | fzf --ansi --delimiter : --preview ''bat --color=always --style=header,grid --highlight-line {2} {1} 2>/dev/null || cat {1}'' --preview-window=right:60%:+{2}/2 --bind ''enter:execute(${EDITOR:-vim} {1} +{2})'''
description: "Search all files in the current directory by content using fzf and ripgrep. This will search all files in the current directory for the specified pattern and display them in an interactive fzf interface, allowing you to preview and edit the results."
arguments: []
tags: ["search", "fzf", "find", "ripgrep", "current", "content", "here"]
source_url: ~
author: ~
author_url: ~
shells: []
