formatter: markdown table

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: false
  color: false
  default: true
  description: true
  escape: true
  hide-empty: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true
