#!/bin/bash

# Completion system
autoload -Uz compinit
compinit

# Set ZSH options
setopt AUTO_CD           # Change directory without cd
setopt EXTENDED_HISTORY  # Record timestamp in history
setopt SHARE_HISTORY     # Share history between sessions
setopt HIST_IGNORE_DUPS  # Don't record duplicates
setopt HIST_IGNORE_SPACE # Don't record commands starting with space

# History configuration
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

## Source tools
# ----------------------------------------------------
# Homebrew shell environment
eval "$(/opt/homebrew/bin/brew shellenv)"

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# Atuin shell history
command -v atuin &>/dev/null && eval "$(atuin init zsh)"

# Zoxide
command -v zoxide &>/dev/null && eval "$(zoxide init zsh)"

# Thefuck
command -v thefuck &>/dev/null && eval $(thefuck --alias)

# Carapace
command -v carapace &>/dev/null && eval "$(carapace zsh)"

# Carapace autocompletion
zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
source <(carapace _carapace)

# Obsidian CLI
if command -v obsidian-cli &>/dev/null; then
  eval "$(obsidian-cli completion zsh)"
fi

# ----------------------------------------------------

# ----------------------------------------------------
# Load Starship prompt if installed
if command -v starship &> /dev/null; then
  eval "$(starship init zsh)"
fi
# ----------------------------------------------------

# ----------------------------------------------------
### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

# Load Zinit
source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit's installer chunk
# ----------------------------------------------------

## Shell configuration
# ----------------------------------------------------
# Create ~/.zsh/local.zsh if it doesn't exist
if [[ ! -f ~/.zsh/local.zsh ]]; then
  mkdir -p ~/.zsh
  touch ~/.zsh/local.zsh
fi

# Load custom configurations
source $HOME/.zshenv
source $HOME/.zsh/local.zsh
source $HOME/.zsh/exports.zsh
source $HOME/.zsh/plugins.zsh
source $HOME/.zsh/vi-mode.zsh
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/functions.zsh
source $HOME/.zsh/custom_shortcuts.zsh
# ----------------------------------------------------
