# Dotfiles Manager Configuration
# This file configures all aspects of the dotfiles management system

# Global settings
global:
  dotfiles_path: "~/dev/dotfiles"
  log_level: "info"
  dry_run: false
  auto_confirm: false
  backup_enabled: true
  backup_suffix: ".backup"
# TUI preferences
tui:
  color_scheme: "default"
  animations: true
  confirm_destructive: true
  show_progress: true
# Stow configuration - Manages symlinked configuration packages
stow:
  packages:
    - name: "config"
      target: "~/.config"
      enabled: true
      priority: 1
    - name: "shell"
      target: "~/"
      enabled: true
      priority: 2
    - name: "git"
      target: "~/"
      enabled: true
      priority: 3
    - name: "docker"
      target: "~/"
      enabled: true
      priority: 4
    - name: "warp"
      target: "~/"
      enabled: true
      priority: 5
    - name: "vscode"
      target: "~/Library/Application Support/Code/User/" # macOS default
      enabled: true
      priority: 6
    - name: "obsidian"
      target: "~/Documents/NotesOfTheGods/" # Adjust to your vault location
      enabled: true
      priority: 7
    - name: "ai_docs"
      target: "~/ai_docs/"
      enabled: true
      priority: 8
    - name: "specs"
      target: "~/specs/"
      enabled: true
      priority: 9
# RSync configuration - Manages file synchronization
rsync:
  enabled: true
  sources:
    - name: "data/claude"
      target: "~/"
      enabled: true
      priority: 1

# Homebrew configuration - Manages package installation
homebrew:
  auto_update: true
  categories:
    core:
      enabled: true
      brewfile: "homebrew/Brewfile"
    apps:
      enabled: true
      brewfile: "homebrew/Brewfile.apps"
    dev:
      enabled: true
      brewfile: "homebrew/Brewfile.dev"
    mas:
      enabled: true
      brewfile: "homebrew/Brewfile.mas"
# Custom Applications - Manages script execution
apps:
  macos_settings:
    enabled: false
    scripts:
      - "data/scripts/mac_settings.sh"
  yazi_packages:
    enabled: true
    scripts:
      - "data/scripts/setup_yazi_packages.sh"
# Global NPM packages - Manages Node.js tools
npm:
  auto_install: true
  auto_update: true
  global_packages:
    - "@anthropic-ai/claude-code"
    - "@mariozechner/snap-happy"
    - "@google/gemini-cli"
    - "@vscode/vsce"
# Global UV packages - Manages Python tools
uv:
  auto_install: true
  auto_update: true
  global_packages:
    - "parllama"
