name: "Greenfield UI Development"
description: "Complete workflow for building new frontend applications from scratch"

triggers:
  - "Building new frontend application"
  - "Creating new UI from scratch"
  - "Developing new SPA or mobile app"
  - "Building new user interface"

phases:
  - name: "Project Initiation"
    description: "Define UI scope and create initial documentation"
    tasks:
      - task: "greenfield-create-project-brief"
        agent: "business-analyst"
        description: "Create comprehensive project brief for UI"
        inputs:
          - "Business requirements"
          - "UI objectives"
          - "Stakeholder input"
        outputs:
          - "Project brief"
          - "UI scope"
          - "Success metrics"
      
      - task: "advanced-elicitation"
        agent: "business-analyst"
        description: "Conduct thorough requirements gathering for UI"
        inputs:
          - "Project brief"
          - "Stakeholder list"
          - "User research"
        outputs:
          - "Detailed requirements"
          - "User personas"
          - "User journey maps"

  - name: "UI/UX Design"
    description: "Design user experience and interface specifications"
    tasks:
      - task: "greenfield-create-ux-wireframes"
        agent: "ux-designer"
        description: "Create comprehensive UX design"
        inputs:
          - "Requirements document"
          - "User personas"
          - "Business objectives"
        outputs:
          - "Wireframes"
          - "User flow diagrams"
          - "Design system"
      
      - task: "greenfield-create-architecture"
        agent: "system-architect"
        description: "Design frontend architecture"
        inputs:
          - "Project brief"
          - "Wireframes"
          - "Technical constraints"
        outputs:
          - "Frontend architecture"
          - "Component structure"
          - "Technology stack"

  - name: "Epic Planning"
    description: "Break down UI into manageable epics"
    tasks:
      - task: "greenfield-create-epic"
        agent: "product-manager"
        description: "Create epics for UI features"
        inputs:
          - "Architecture document"
          - "Wireframes"
          - "Project brief"
        outputs:
          - "Epic documents"
          - "Feature roadmap"
          - "Release plan"

  - name: "Story Development"
    description: "Create detailed user stories for UI development"
    tasks:
      - task: "greenfield-create-story"
        agent: "product-owner"
        description: "Create detailed UI stories"
        inputs:
          - "Epic documents"
          - "Architecture document"
          - "Wireframes"
        outputs:
          - "User stories"
          - "Component specifications"
          - "Story estimates"
      
      - task: "validate-story"
        agent: "quality-assurance"
        description: "Validate stories for UI completeness"
        inputs:
          - "User stories"
          - "Architecture document"
          - "Quality standards"
        outputs:
          - "Validated stories"
          - "UI test strategy"
          - "Quality plan"

  - name: "Implementation"
    description: "Develop and test the UI"
    tasks:
      - task: "execute-checklist"
        agent: "senior-developer"
        description: "Implement UI following best practices"
        inputs:
          - "Validated stories"
          - "Architecture document"
          - "Design specifications"
        outputs:
          - "UI implementation"
          - "Component library"
          - "UI tests"

quality_gates:
  - name: "Project Brief Approval"
    description: "Ensure UI project is viable and well-defined"
    checklist: "pm-checklist"
    required_approvers: ["product-manager", "business-analyst"]
  
  - name: "Architecture Review"
    description: "Validate frontend architecture"
    checklist: "architect-checklist"
    required_approvers: ["system-architect", "ux-designer"]
  
  - name: "Epic Validation"
    description: "Confirm epics support UI goals"
    checklist: "pm-checklist"
    required_approvers: ["product-manager", "product-owner"]
  
  - name: "Story Readiness"
    description: "Ensure stories are ready for UI development"
    checklist: "story-dod-checklist"
    required_approvers: ["product-owner", "quality-assurance"]

success_criteria:
  - "All UI objectives met"
  - "User experience meets design standards"
  - "Frontend architecture supports scalability"
  - "All stories meet definition of done"
  - "Performance benchmarks achieved"
  - "Accessibility requirements satisfied"

team_composition:
  required:
    - "business-analyst"
    - "ux-designer"
    - "system-architect"
    - "product-manager"
    - "product-owner"
    - "senior-developer"
    - "quality-assurance"
  optional:
    - "scrum-master"

estimated_duration: "6-12 weeks"
complexity: "medium-high"