# Dotfiles Manager Theme Configuration
# Customize the appearance of the TUI interface

themes:
  default:
    primary: "#007acc"
    secondary: "#00d7ff"
    success: "#00ff00"
    warning: "#ffaa00"
    error: "#ff0000"
    background: "#1e1e1e"
    foreground: "#ffffff"
  
  light:
    primary: "#0066cc"
    secondary: "#0099cc"
    success: "#008800"
    warning: "#cc6600"
    error: "#cc0000"
    background: "#ffffff"
    foreground: "#000000"
  
  cyberpunk:
    primary: "#ff007f"
    secondary: "#00ffff"
    success: "#00ff41"
    warning: "#ffaa00"
    error: "#ff073a"
    background: "#0d1117"
    foreground: "#00ff41"
  
  solarized_dark:
    primary: "#268bd2"
    secondary: "#2aa198"
    success: "#859900"
    warning: "#b58900"
    error: "#dc322f"
    background: "#002b36"
    foreground: "#839496"
    
  solarized_light:
    primary: "#268bd2"
    secondary: "#2aa198"
    success: "#859900"
    warning: "#b58900"
    error: "#dc322f"
    background: "#fdf6e3"
    foreground: "#657b83"