#!/bin/bash
set -euo pipefail

readonly AWS_LOGIN_PROFILE="mbastakis"
readonly BUCKET="mbastakis-homeserver-opentofu-state"
readonly REGION="eu-central-1"
readonly STATE_KEY="homeserver/bootstrap/terraform.tfstate"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR
readonly BACKEND_FILE="$SCRIPT_DIR/backend.generated.tf"

usage() {
    cat >&2 <<EOF
Usage: $0 [tofu apply args...]

Creates or adopts the fixed S3 backend for homeserver OpenTofu state using
OpenTofu configuration, then migrates this bootstrap stack's local state into
that bucket.

Backend:
  AWS profile: $AWS_LOGIN_PROFILE
  S3 bucket:   $BUCKET
  Region:      $REGION
  State key:   $STATE_KEY
  Locking:     S3 native lockfile

Examples:
  $0
  $0 -auto-approve
EOF
}

log_info() {
    printf '\033[0;34m[INFO]\033[0m %s\n' "$*" >&2
}

log_warning() {
    printf '\033[0;33m[WARN]\033[0m %s\n' "$*" >&2
}

log_error() {
    printf '\033[0;31m[ERROR]\033[0m %s\n' "$*" >&2
}

aws_cmd() {
    aws-login exec "$AWS_LOGIN_PROFILE" -- aws "$@"
}

tofu_cmd() {
    aws-login exec "$AWS_LOGIN_PROFILE" -- tofu -chdir="$SCRIPT_DIR" "$@"
}

write_backend_file() {
    cat >"$BACKEND_FILE" <<EOF
# Generated by infra/terraform/bootstrap/create-state-backend.sh.
# Do not commit. The first bootstrap apply intentionally runs without this
# file so OpenTofu can create the S3 backend bucket using local state.
terraform {
  backend "s3" {}
}
EOF
}

state_has_resource() {
    local address="$1"
    tofu_cmd state show "$address" &>/dev/null
}

import_if_missing() {
    local address="$1"
    local id="$2"

    if state_has_resource "$address"; then
        log_info "State already tracks $address"
        return 0
    fi

    log_info "Importing existing AWS resource into local bootstrap state: $address"
    tofu_cmd import -input=false "$address" "$id"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        --)
            shift
            break
            ;;
        *)
            break
            ;;
    esac
done

log_info "Using fixed aws-login profile: $AWS_LOGIN_PROFILE"
log_info "Bootstrap stack directory: $SCRIPT_DIR"

bucket_exists=false
if aws_cmd s3api head-bucket --bucket "$BUCKET" --region "$REGION" &>/dev/null; then
    bucket_exists=true
    log_info "State bucket already exists and is accessible: $BUCKET"

    if aws_cmd s3api head-object --bucket "$BUCKET" --key "$STATE_KEY" &>/dev/null; then
        log_error "Remote bootstrap state already exists at s3://$BUCKET/$STATE_KEY"
        log_error "Use task tf:bootstrap:plan or task tf:bootstrap:apply for steady-state changes."
        exit 1
    fi
else
    log_info "State bucket does not exist yet; OpenTofu will create it with local state."
fi

log_info "Initializing bootstrap stack with local state."
rm -f "$BACKEND_FILE"
tofu_cmd init -input=false -reconfigure

if [[ "$bucket_exists" == "true" ]]; then
    log_info "Adopting existing state bucket resources before reconciliation."
    import_if_missing aws_s3_bucket.opentofu_state "$BUCKET"

    if aws_cmd s3api get-public-access-block --bucket "$BUCKET" &>/dev/null; then
        import_if_missing aws_s3_bucket_public_access_block.opentofu_state "$BUCKET"
    else
        log_warning "No existing public access block found; OpenTofu will create it."
    fi

    if aws_cmd s3api get-bucket-versioning --bucket "$BUCKET" &>/dev/null; then
        import_if_missing aws_s3_bucket_versioning.opentofu_state "$BUCKET"
    else
        log_warning "No existing versioning configuration found; OpenTofu will create it."
    fi

    if aws_cmd s3api get-bucket-encryption --bucket "$BUCKET" &>/dev/null; then
        import_if_missing aws_s3_bucket_server_side_encryption_configuration.opentofu_state "$BUCKET"
    else
        log_warning "No existing encryption configuration found; OpenTofu will create it."
    fi

    if aws_cmd s3api get-bucket-ownership-controls --bucket "$BUCKET" &>/dev/null; then
        import_if_missing aws_s3_bucket_ownership_controls.opentofu_state "$BUCKET"
    else
        log_warning "No existing ownership controls found; OpenTofu will create them."
    fi

    if aws_cmd s3api get-bucket-policy --bucket "$BUCKET" &>/dev/null; then
        import_if_missing aws_s3_bucket_policy.opentofu_state "$BUCKET"
    else
        log_warning "No existing bucket policy found; OpenTofu will create one."
    fi
fi

log_info "Applying bootstrap OpenTofu configuration with local state."
tofu_cmd apply "$@"

if ! state_has_resource aws_s3_bucket.opentofu_state; then
    log_error "Bootstrap state does not track aws_s3_bucket.opentofu_state; refusing to migrate."
    log_error "If the apply was cancelled, rerun this command and approve the plan."
    exit 1
fi

if ! aws_cmd s3api head-bucket --bucket "$BUCKET" --region "$REGION" &>/dev/null; then
    log_error "State bucket is still not accessible after apply: $BUCKET"
    exit 1
fi

log_info "Generating S3 backend block and migrating local state to S3."
write_backend_file

tofu_cmd init \
    -input=false \
    -migrate-state \
    -force-copy \
    -backend-config="bucket=$BUCKET" \
    -backend-config="key=$STATE_KEY" \
    -backend-config="region=$REGION" \
    -backend-config="encrypt=true" \
    -backend-config="use_lockfile=true"

cat <<EOF

OpenTofu state backend is ready and managed by the bootstrap stack.

Backend config keys:
  bucket       = $BUCKET
  key          = $STATE_KEY
  region       = $REGION
  encrypt      = true
  use_lockfile = true

Next commands:
  task tf:bootstrap:plan
  task tf:aws-foundation:init
  task tf:truenas:init
EOF
