from __future__ import annotations

import stat
from pathlib import Path
from typing import cast

import pytest

from homeserver_iac.models.secrets import SecretMetadataDesiredState
from homeserver_iac.runtime import OperationalError
from homeserver_iac.secrets import (
    BwsClient,
    SecretResolver,
    list_secrets,
    list_targets,
    render_env_file,
)


def desired_state(
    *, secret_id: str | None = "11111111-1111-4111-8111-111111111111"
) -> SecretMetadataDesiredState:
    return SecretMetadataDesiredState.model_validate(
        {
            "schema_version": 1,
            "ownership": {"scope": "secrets.bws_metadata", "mode": "bounded"},
            "project": {
                "name": "homeserver",
                "id": "22222222-2222-4222-8222-222222222222",
            },
            "secrets": {
                "demo_secret": {
                    "key": "homeserver/demo/secret",
                    "id": secret_id,
                    "owner": "demo.service",
                    "lifecycle": "generated",
                    "consumers": ["demo-target"],
                    "generation_method": "Generate with a CSPRNG.",
                    "rotation_runbook": "docs/runbooks/homeserver-secret-rotation.md",
                    "purpose": "Test fixture",
                }
            },
            "targets": {"demo-target": {"DEMO_SECRET": {"secret_ref": {"alias": "demo_secret"}}}},
        }
    )


class FakeBwsClient:
    def __init__(self) -> None:
        self.requested_ids: list[str] = []

    def secret_ids_by_key(self, project_id: str) -> dict[str, str]:
        assert project_id == "22222222-2222-4222-8222-222222222222"
        return {"homeserver/demo/secret": "33333333-3333-4333-8333-333333333333"}

    def secret_value(self, secret_id: str) -> str:
        self.requested_ids.append(secret_id)
        return "fixture-secret"


def resolver(
    desired: SecretMetadataDesiredState, client: FakeBwsClient, environment: dict[str, str]
) -> SecretResolver:
    return SecretResolver(desired, cast(BwsClient, client), environment=environment)


def test_secret_metadata_listing_is_deterministic_and_value_free() -> None:
    desired = desired_state()

    assert list_targets(desired) == ("demo-target",)
    assert list_secrets(desired) == (
        (
            "demo_secret",
            "homeserver/demo/secret",
            "11111111-1111-4111-8111-111111111111",
        ),
    )


def test_target_resolution_uses_committed_bws_id_without_printing_value() -> None:
    client = FakeBwsClient()

    values = resolver(desired_state(), client, {}).target_environment("demo-target")

    assert values == {"DEMO_SECRET": "fixture-secret"}
    assert client.requested_ids == ["11111111-1111-4111-8111-111111111111"]


def test_target_resolution_uses_environment_before_key_lookup() -> None:
    client = FakeBwsClient()

    values = resolver(
        desired_state(secret_id=None), client, {"DEMO_SECRET": "environment-secret"}
    ).target_environment("demo-target")

    assert values == {"DEMO_SECRET": "environment-secret"}
    assert client.requested_ids == []


def test_rendered_env_file_is_restricted_and_shell_quoted(tmp_path: Path) -> None:
    output = tmp_path / "nested/demo.env"

    render_env_file("demo-target", {"DEMO_SECRET": "has'a space"}, output)

    assert stat.S_IMODE(output.stat().st_mode) == 0o600
    assert output.read_text() == (
        "# Generated by homeserver-iac. Do not commit.\n"
        "# Target: demo-target\n"
        "export DEMO_SECRET='has'\\''a space'\n"
    )


def test_unknown_target_error_does_not_contain_resolved_secret() -> None:
    client = FakeBwsClient()

    with pytest.raises(OperationalError, match="unknown secret target") as raised:
        resolver(desired_state(), client, {}).target_environment("missing")

    assert "fixture-secret" not in str(raised.value)
