FROM --platform=linux/amd64 docker.io/library/debian:bookworm-slim@sha256:63a496b5d3b99214b39f5ed70eb71a61e590a77979c79cbee4faf991f8c0783e

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends \
        bzip2 ca-certificates file g++ gawk gcc gettext make patch perl python3 \
        python3-distutils rsync squashfs-tools unzip wget zstd \
    && rm -rf /var/lib/apt/lists/* \
    && useradd --create-home --uid 1000 builder

USER builder
WORKDIR /home/builder/work
