after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

# Start AeroSpace at login
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 50
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focus-changed = ['move-mouse window-lazy-center'] # Mouse lazily follows any focus (window or workspace)
[key-mapping]
    preset = 'dvorak'

# Workspace A
[[on-window-detected]]
if.app-name-regex-substring = 'Microsoft Edge'
run = 'move-node-to-workspace a'

[[on-window-detected]]
if.app-name-regex-substring = 'Vivaldi'
run = 'move-node-to-workspace a'

[[on-window-detected]]
if.app-name-regex-substring = 'Obsidian'
run = 'move-node-to-workspace a'

# Workspace O
[[on-window-detected]]
if.app-name-regex-substring = 'Code - Insiders'
run = 'move-node-to-workspace o'

[[on-window-detected]]
if.app-name-regex-substring = 'Code'
run = 'move-node-to-workspace o'

# Workspace E
[[on-window-detected]]
if.app-name-regex-substring = 'Discord'
run = 'move-node-to-workspace e'

[[on-window-detected]]
if.app-name-regex-substring = 'Mail'
run = 'move-node-to-workspace e'

[[on-window-detected]]
if.app-name-regex-substring = 'Bitwarden'
run = 'move-node-to-workspace e'

# Workspace U
[[on-window-detected]]
if.app-name-regex-substring = 'Outlook'
run = 'move-node-to-workspace u'

[[on-window-detected]]
if.app-name-regex-substring = 'ChatGPT'
run = 'move-node-to-workspace u'

[[on-window-detected]]
if.app-name-regex-substring = 'Microsoft Teams'
run = 'move-node-to-workspace u'

[[on-window-detected]]
if.app-name-regex-substring = 'Spotify'
run = 'move-node-to-workspace u'

[[on-window-detected]]
if.app-name-regex-substring = 'Claude'
run = 'move-node-to-workspace u'

[[on-window-detected]]
if.app-name-regex-substring = 'Gemini'
run = 'move-node-to-workspace u'

[[on-window-detected]]
if.app-name-regex-substring = 'GitHub'
run = 'move-node-to-workspace u'


# Floating windows

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'AppCleaner'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'System Preferences'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'DC:Dark Legion'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Chess'
run = 'layout floating'


[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      80


[mode.main.binding]

alt-ctrl-shift-f = 'fullscreen'
alt-ctrl-f = 'layout floating tiling'

# alt-shift-left = 'join-with left'
# alt-shift-down = 'join-with down'
# alt-shift-up = 'join-with up'
# alt-shift-right = 'join-with right'

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-t = 'focus down'
alt-n = 'focus up'
alt-s = 'focus right'

alt-shift-h = 'move left'
alt-shift-t = 'move down'
alt-shift-n = 'move up'
alt-shift-s = 'move right'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

alt-a = 'workspace a'
alt-o = 'workspace o'
alt-e = 'workspace e'
alt-u = 'workspace u'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'

alt-shift-a = 'move-node-to-workspace a --focus-follows-window'
alt-shift-o = 'move-node-to-workspace o --focus-follows-window'
alt-shift-e = 'move-node-to-workspace e --focus-follows-window'
alt-shift-u = 'move-node-to-workspace u --focus-follows-window'
alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']