return function(theme)
  local ui = theme.ui
  local diag = theme.diagnostic
  local vcs = theme.vcs
  local diff = theme.diff

  return {
    Normal = { fg = ui.text, bg = ui.bg },
    NormalNC = { fg = ui.text_dim, bg = ui.bg_inactive },
    NormalFloat = { fg = ui.text, bg = ui.surface },
    FloatBorder = { fg = ui.overlay_high, bg = ui.surface },
    FloatTitle = { fg = ui.accent, bg = ui.surface, bold = true },
    ColorColumn = { bg = ui.bg_inactive },
    Cursor = { fg = ui.bg, bg = ui.accent },
    CursorLine = { bg = ui.bg_inactive },
    CursorColumn = { bg = ui.bg_inactive },
    CursorLineNr = { fg = ui.accent, bold = true },
    LineNr = { fg = ui.disabled },
    SignColumn = { bg = ui.bg },
    FoldColumn = { fg = ui.muted, bg = ui.bg },
    Folded = { fg = ui.text_dim, bg = ui.surface },
    Visual = { bg = ui.overlay },
    Search = { fg = ui.text, bg = ui.search },
    CurSearch = { fg = ui.text, bg = ui.search_current, bold = true },
    IncSearch = { fg = ui.text, bg = ui.search_current, bold = true },
    Substitute = { fg = ui.text, bg = ui.search_current },
    MatchParen = { fg = ui.text, bg = ui.overlay_high, bold = true },
    Pmenu = { fg = ui.text, bg = ui.surface },
    PmenuSel = { fg = ui.text, bg = ui.overlay, bold = true },
    PmenuSbar = { bg = ui.surface },
    PmenuThumb = { bg = ui.overlay_high },
    StatusLine = { fg = ui.text, bg = ui.overlay },
    StatusLineNC = { fg = ui.muted, bg = ui.bg_inactive },
    TabLine = { fg = ui.muted, bg = ui.bg_inactive },
    TabLineSel = { fg = ui.accent, bg = ui.surface, bold = true },
    TabLineFill = { bg = ui.bg_deep },
    WinSeparator = { fg = ui.overlay_high },
    Directory = { fg = ui.accent_secondary },
    Title = { fg = ui.accent, bold = true },
    NonText = { fg = ui.disabled },
    Whitespace = { fg = ui.disabled },
    SpecialKey = { fg = ui.disabled },
    Conceal = { fg = ui.muted },
    ErrorMsg = { fg = diag.error },
    WarningMsg = { fg = diag.warn },
    MoreMsg = { fg = diag.info },
    Question = { fg = ui.accent_secondary },
    DiagnosticError = { fg = diag.error },
    DiagnosticWarn = { fg = diag.warn },
    DiagnosticInfo = { fg = diag.info },
    DiagnosticHint = { fg = diag.hint },
    DiagnosticUnderlineError = { undercurl = true, sp = diag.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = diag.warn },
    DiagnosticUnderlineInfo = { undercurl = true, sp = diag.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = diag.hint },
    Added = { fg = vcs.add },
    Changed = { fg = vcs.change },
    Removed = { fg = vcs.delete },
    DiffAdd = { fg = vcs.add, bg = diff.add },
    DiffChange = { fg = vcs.change, bg = diff.change },
    DiffDelete = { fg = vcs.delete, bg = diff.delete },
    DiffText = { fg = ui.text, bg = diff.text, bold = true },
  }
end
