return function(theme)
  local syn = theme.syntax
  local ui = theme.ui
  local diag = theme.diagnostic

  return {
    Comment = { fg = syn.comment, italic = true },
    Constant = { fg = syn.constant },
    String = { fg = syn.string },
    Character = { fg = syn.string },
    Number = { fg = syn.constant },
    Boolean = { fg = syn.constant },
    Float = { fg = syn.constant },
    Identifier = { fg = syn.text },
    Function = { fg = syn.func },
    Statement = { fg = syn.keyword },
    Conditional = { fg = syn.keyword },
    Repeat = { fg = syn.keyword },
    Label = { fg = syn.keyword },
    Operator = { fg = syn.punctuation },
    Keyword = { fg = syn.keyword, bold = true },
    Exception = { fg = syn.keyword },
    PreProc = { fg = syn.builtin },
    Include = { fg = syn.keyword },
    Define = { fg = syn.keyword },
    Macro = { fg = syn.builtin },
    Type = { fg = syn.type },
    StorageClass = { fg = syn.keyword },
    Structure = { fg = syn.type },
    Typedef = { fg = syn.type },
    Special = { fg = syn.builtin },
    Delimiter = { fg = syn.punctuation },
    Underlined = { fg = ui.accent_secondary, underline = true },
    Error = { fg = diag.error },
    Todo = { fg = ui.accent, bg = ui.surface, bold = true },

    ["@variable"] = { fg = syn.text },
    ["@variable.builtin"] = { fg = syn.builtin },
    ["@variable.parameter"] = { fg = ui.text_dim, italic = true },
    ["@constant"] = { fg = syn.constant },
    ["@constant.builtin"] = { fg = syn.builtin },
    ["@string"] = { fg = syn.string },
    ["@number"] = { fg = syn.constant },
    ["@boolean"] = { fg = syn.constant },
    ["@function"] = { fg = syn.func },
    ["@function.call"] = { fg = syn.func },
    ["@function.builtin"] = { fg = syn.builtin },
    ["@constructor"] = { fg = syn.builtin },
    ["@keyword"] = { fg = syn.keyword, bold = true },
    ["@keyword.function"] = { fg = syn.keyword },
    ["@keyword.return"] = { fg = syn.keyword },
    ["@type"] = { fg = syn.type },
    ["@type.builtin"] = { fg = syn.builtin },
    ["@property"] = { fg = syn.text },
    ["@attribute"] = { fg = ui.accent_secondary },
    ["@operator"] = { fg = syn.punctuation },
    ["@punctuation.delimiter"] = { fg = syn.punctuation },
    ["@punctuation.bracket"] = { fg = syn.punctuation },
    ["@punctuation.special"] = { fg = ui.text_dim },
    ["@markup.heading"] = { fg = ui.accent, bold = true },
    ["@markup.link"] = { fg = ui.accent_secondary, underline = true },
    ["@markup.raw"] = { fg = syn.string },
  }
end
