# AgentOS Configuration for OpenCode Integration

agentos:
  enabled: true
  version: "1.0"
  
  # Three-Layer Context Architecture
  context_layers:
    standards:
      path: "~/.config/opencode/standards"
      always_load: ["bmad/methodology-lite", "coding/style-guides"]
      conditional_load:
        web_project: ["security/secure-coding", "performance/optimization"]
        api_project: ["apis/patterns", "security/secure-coding"]
        mobile_project: ["mobile/patterns", "performance/optimization"]
    
    products:
      path: "~/.config/opencode/products"
      detection: "auto"
      fallback: "web-apps"
    
    specs:
      path: "~/.config/opencode/specs"
      source: "project_context"
      cache_duration: "1h"

  # Smart Context Loading
  context_optimization:
    smart_loading: true
    conditional_loading: true
    cache_enabled: true
    auto_detection: true
    token_reduction_target: 60
    relevance_threshold: 90
    cache_duration: "1h"
    
    # Cache Management Policies
    cache_management:
      location: "~/.config/opencode/cache"
      max_size: "100MB"
      cleanup_interval: "6h"
      compression: true
      invalidation_strategy: "lru"
      preload_common_patterns: true
      
      # Cache Layers
      layers:
        standards:
          duration: "24h"
          priority: "high"
          compression: true
        products:
          duration: "12h"
          priority: "medium"
          compression: true
        specs:
          duration: "1h"
          priority: "low"
          compression: false
      
      # Cache Optimization
      optimization:
        lazy_loading: true
        predictive_loading: true
        context_compression: true
        deduplication: true
        
      # Cache Validation
      validation:
        integrity_checks: true
        consistency_validation: true
        performance_monitoring: true

  # Quality Gates
  quality_gates:
    enabled: true
    gates:
      - "standards_compliance"
      - "spec_alignment" 
      - "bmad_validation"
      - "security_check"
      - "performance_validation"
    
    thresholds:
      standards_compliance: 100
      spec_alignment: 95
      bmad_validation: 100
      security_check: 100
      performance_validation: 85

  # Subagent System
  subagents:
    enabled: true
    auto_spawn: true
    coordination: "orchestrated"
    
    available:
      - name: "context-optimizer"
        role: "context_optimization"
        auto_spawn_conditions: ["context_loading", "performance_optimization"]
      
      - name: "spec-analyzer"
        role: "specification_analysis"
        auto_spawn_conditions: ["spec_creation", "requirements_analysis"]
      
      - name: "quality-enforcer"
        role: "quality_validation"
        auto_spawn_conditions: ["quality_gates", "standards_validation"]

  # Project Detection Rules
  project_detection:
    web_application:
      files: ["package.json", "src/", "public/", "index.html"]
      patterns: ["react", "vue", "angular", "svelte"]
      context_load:
        standards: ["coding/style-guides", "security/secure-coding", "performance/optimization"]
        products: ["web-apps/patterns"]
    
    api_service:
      files: ["api/", "routes/", "controllers/", "openapi.yaml", "swagger.json"]
      patterns: ["express", "fastapi", "rails", "django"]
      context_load:
        standards: ["coding/style-guides", "security/secure-coding"]
        products: ["apis/patterns"]
    
    mobile_app:
      files: ["ios/", "android/", "mobile/", "react-native/", "flutter/"]
      patterns: ["react-native", "flutter", "ionic", "cordova"]
      context_load:
        standards: ["coding/style-guides", "performance/optimization"]
        products: ["mobile/patterns"]

  # Integration Settings
  integration:
    bmad_methodology: true
    existing_workflows: "enhance"
    backward_compatibility: true
    migration_mode: "gradual"

  # Error Handling and Fallback Mechanisms
  error_handling:
    enabled: true
    
    # Context Loading Errors
    context_loading:
      retry_attempts: 3
      retry_delay: "2s"
      timeout: 30
      fallback_sources: ["cache", "lite_versions", "defaults"]
      graceful_degradation: true
      
    # Quality Gate Failures
    quality_gates:
      failure_actions: ["notify", "fallback", "manual_review"]
      escalation_threshold: 3
      fallback_quality_level: "minimum_viable"
      auto_recovery: true
      
    # Agent Coordination Errors
    agent_coordination:
      subagent_spawn_failure: "continue_with_main_agent"
      communication_timeout: 15
      coordination_retry: 2
      fallback_mode: "single_agent"
      
    # Cache System Errors
    cache_system:
      corruption_detection: true
      auto_repair: true
      backup_restoration: true
      fallback_to_source: true
      
    # Performance Degradation
    performance:
      slow_response_threshold: 10
      memory_limit_action: "optimize_context"
      token_limit_action: "compress_context"
      emergency_mode: "minimal_context"

# Performance Monitoring
monitoring:
  enabled: true
  storage:
    location: "~/.config/opencode/metrics"
    retention: "30d"
    format: "json"
    compression: true
  
  logging:
    location: "~/.config/opencode/logs"
    level: "info"
    rotation: "daily"
    max_size: "10MB"
  
  alerts:
    token_usage_threshold: 10000
    context_loading_timeout: 30
    cache_miss_rate: 20
    quality_gate_failure_rate: 10
    agent_coordination_failure: 5
  
  context_efficiency:
    track_token_usage: true
    track_relevance_score: true
    track_loading_time: true
    track_cache_hit_rate: true
    track_compression_ratio: true
    baseline_measurements: true
  
  quality_metrics:
    track_gate_pass_rate: true
    track_compliance_score: true
    track_defect_rate: true
    track_validation_time: true
    track_quality_trends: true
  
  agent_performance:
    track_coordination_efficiency: true
    track_subagent_utilization: true
    track_workflow_completion: true
    track_response_time: true
    track_success_rate: true
    track_resource_usage: true
  
  reporting:
    dashboard_enabled: true
    dashboard_location: "~/.config/opencode/quality/reports/performance-dashboard.md"
    update_interval: "1h"
    export_formats: ["json", "csv", "markdown"]